stages:
  - pages
pages:
  image: node:14.0
  stage: pages
  cache:
    paths:
    - node_modules/
  before_script:
    - node -v
    - npm -v
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - cd public
    - ls
    - cd ../
    - cp "$labuploader" ./labuploader
    - chmod 0600 labuploader
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -Cr -i labuploader public labUploader@huching.cn:/var/www/lab/
  artifacts:
    paths:
      - public
  only:
    - master