stages:
  - pages
pages:
  image: node:14.0
  stage: pages
  cache:
    paths:
    - node_modules/
  before_script:
    - node -v
    - npm -v
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - cd public
    - ls
    - cd ../
    - echo "$labuploader" > "$(pwd)/labuploader"
    - cat "$(pwd)/labuploader"
    - scp -vCq -r -i "$(pwd)/labuploader" ./public labUploader@huching.cn:/var/www/lab 
  artifacts:
    paths:
      - public
  only:
    - master