stages:
  - pages
  - docker
pages:
  image: node:14.0
  stage: pages
  cache:
    paths:
    - node_modules/
  before_script:
    - node -v
    - npm -v
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - cd public
    # - ls
    # - cd ../
    # - cp "$labuploader" ./labuploader
    # - chmod 0600 labuploader
    # - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -Cr -i labuploader public labUploader@huching.cn:/var/www/lab/
    - curl -X POST "${TG_URL}" -d "chat_id=${TG_CHAT_ID}&text=gitLab%20%E4%B8%8A%E7%9A%84%20project-react-sync%20%E5%B7%B2%E7%BB%8F%E9%83%A8%E7%BD%B2%E5%AE%8C%E6%88%90%E5%95%A6"
  artifacts:
    paths:
      - public
  only:
    - master
docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker info
    - cat "$dockerioToken" | docker login --username hzsq --password-stdin
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - cd public
    - docker build -t hzsq/huxi-lab:${tag} .
    - docker push hzsq/huxi-lab:${tag}
    - docker push hzsq/huxi-lab:${tag} hzsq/huxi-lab:latest