stages:
  - pages
pages:
  image: node:14.0
  stage: pages
  cache:
    paths:
    - node_modules/
  before_script:
    - node -v
    - npm -v
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - cd public
    - ls
    - echo "$KUBE_CA_PEM" > "$(pwd)/labuploader"
    - chmod 600 ./labuploader
    - scp -vCq -r -i ./labuploader  ./dist  labUploader@huching.cn:/var/www/lab 
  artifacts:
    paths:
      - public
  only:
    - master