
stages:
  - pages
pages:
  image: node:14.0
  stage: pages
  cache:
    paths:
    - node_modules/
  before_script:
    - node -v
    - npm -v
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - cd public
    - ls
  artifacts:
    paths:
      - public
  only:
    - master